# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-05 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Boxes',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('checkTime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('isExist', models.BooleanField(default=False)),
                ('isChecked', models.BooleanField()),
                ('boxId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Box')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutgoingOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('checkTime', models.DateTimeField(blank=True, null=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(max_length=30)),
                ('isFragile', models.BooleanField(default=False)),
                ('isChecked', models.BooleanField()),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.IncomingOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='user', max_length=11)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('remainingCapacity', models.IntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.WarehouseType'),
        ),
        migrations.AddField(
            model_name='user',
            name='warehouseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Warehouse'),
        ),
        migrations.AddField(
            model_name='package',
            name='warehouseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Warehouse'),
        ),
        migrations.AddField(
            model_name='outgoingorder',
            name='providerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Provider'),
        ),
        migrations.AddField(
            model_name='outgoingorder',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.User'),
        ),
        migrations.AddField(
            model_name='item',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.OutgoingOrder'),
        ),
        migrations.AddField(
            model_name='incomingorder',
            name='ownerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Owner'),
        ),
        migrations.AddField(
            model_name='incomingorder',
            name='providerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Provider'),
        ),
        migrations.AddField(
            model_name='incomingorder',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.User'),
        ),
        migrations.AddField(
            model_name='box',
            name='packageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Package'),
        ),
    ]
