# Generated by Django 2.0.5 on 2018-06-26 07:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 6, 38, 574150, tzinfo=utc), editable=False)),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 6, 38, 574150, tzinfo=utc))),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 6, 38, 574150, tzinfo=utc), editable=False)),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 6, 38, 574150, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 6, 38, 574150, tzinfo=utc), editable=False)),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 6, 38, 574150, tzinfo=utc))),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 6, 38, 574150, tzinfo=utc), editable=False)),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 6, 38, 574150, tzinfo=utc))),
                ('type', models.CharField(max_length=30)),
                ('isFragile', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 6, 38, 574150, tzinfo=utc), editable=False)),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 6, 38, 574150, tzinfo=utc))),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 6, 38, 379395, tzinfo=utc), editable=False)),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 6, 38, 379395, tzinfo=utc))),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='user', max_length=11)),
                ('password', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 6, 38, 379395, tzinfo=utc), editable=False)),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 6, 38, 379395, tzinfo=utc))),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('remainingCapacity', models.IntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='WarehouseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingOrder',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='whss.Order')),
                ('pkgQty', models.IntegerField()),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingPackage',
            fields=[
                ('packageId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='whss.Package')),
                ('checkInTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingOrder',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='whss.Order')),
                ('pkgQty', models.IntegerField()),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingPackage',
            fields=[
                ('packageId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='whss.Package')),
                ('checkOutTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.WarehouseType'),
        ),
        migrations.AddField(
            model_name='user',
            name='warehouseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Warehouse'),
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='wantedWarehouseType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.WarehouseType'),
        ),
        migrations.AddField(
            model_name='package',
            name='warehouseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Warehouse'),
        ),
        migrations.AddField(
            model_name='order',
            name='packageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Package'),
        ),
        migrations.AddField(
            model_name='order',
            name='providerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Provider'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outgoingpackage',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.User'),
        ),
        migrations.AddField(
            model_name='incomingpackage',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.User'),
        ),
    ]
