# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-28 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingorder',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='incomingorder',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingorder',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingorder',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
