# Generated by Django 2.0.5 on 2018-05-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whss', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
