# Generated by Django 2.0.5 on 2018-06-26 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('whss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 7, 16, 155819, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 7, 16, 155819, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 7, 16, 155819, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 7, 16, 155819, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='owner',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 7, 16, 155819, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 7, 16, 155819, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='package',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 7, 16, 155819, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 7, 16, 155819, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='provider',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 7, 16, 155819, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 7, 16, 155819, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 7, 15, 999901, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 7, 15, 999901, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 7, 15, 999901, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 7, 7, 15, 999901, tzinfo=utc)),
        ),
    ]
