# Generated by Django 2.0.5 on 2018-05-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whss', '0002_auto_20180529_1219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
