# Generated by Django 2.0.5 on 2018-05-29 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whss', '0003_auto_20180529_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('isFragile', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PackageIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkInTime', models.DateTimeField(default=datetime.datetime.now)),
                ('packageId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whss.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkOutTime', models.DateTimeField(default=datetime.datetime.now)),
                ('packageId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whss.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('remainingCapacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='fname',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='user', max_length=11),
        ),
        migrations.CreateModel(
            name='IncomingOrder',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='whss.Order')),
                ('pkgQty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingOrder',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='whss.Order')),
                ('pkgQty', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.WarehouseType'),
        ),
        migrations.AddField(
            model_name='packageout',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whss.User'),
        ),
        migrations.AddField(
            model_name='packagein',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.User'),
        ),
        migrations.AddField(
            model_name='package',
            name='warehouseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Warehouse'),
        ),
        migrations.AddField(
            model_name='package',
            name='warehouseType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.WarehouseType'),
        ),
        migrations.AddField(
            model_name='order',
            name='packageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Package'),
        ),
        migrations.AddField(
            model_name='order',
            name='providerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.Provider'),
        ),
        migrations.AddField(
            model_name='user',
            name='warehouseId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='whss.Warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.IncomingOrder'),
        ),
        migrations.AddField(
            model_name='customer',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.OutgoingOrder'),
        ),
    ]
