# Generated by Django 2.0.5 on 2018-06-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whss', '0003_auto_20180626_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='package',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
