# Generated by Django 2.0.5 on 2018-06-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whss', '0004_auto_20180626_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
