# Generated by Django 2.0.5 on 2018-06-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whss', '0005_auto_20180626_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='created',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
