# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-05 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whss', '0006_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingPackage',
            fields=[
                ('packageId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='whss.Package')),
                ('checkInTime', models.DateTimeField(default=datetime.datetime.now)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.User')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingPackage',
            fields=[
                ('packageId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='whss.Package')),
                ('checkOutTime', models.DateTimeField(default=datetime.datetime.now)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whss.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='packagein',
            name='packageId',
        ),
        migrations.RemoveField(
            model_name='packagein',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='packageout',
            name='packageId',
        ),
        migrations.RemoveField(
            model_name='packageout',
            name='userId',
        ),
        migrations.AlterField(
            model_name='incomingorder',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='whss.Order'),
        ),
        migrations.AlterField(
            model_name='outgoingorder',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='whss.Order'),
        ),
        migrations.DeleteModel(
            name='PackageIn',
        ),
        migrations.DeleteModel(
            name='PackageOut',
        ),
    ]
