# Generated by Django 2.0.5 on 2018-06-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whss', '0006_auto_20180626_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
