# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-05 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whss', '0007_auto_20180605_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
