# Generated by Django 2.0.5 on 2018-06-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whss', '0008_auto_20180626_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
