# Generated by Django 2.0.5 on 2018-06-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whss', '0009_auto_20180626_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='last_modified',
            field=models.DateTimeField(editable=False),
        ),
    ]
