# Generated by Django 2.0.5 on 2018-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whss', '0011_auto_20180626_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
